### ISSUE TITLE
 Enforce Google Java Style.

### ISSUE THREAD

**Issue by Clivern** [Clivern/wit-java#3]

**Comment by IEnoobong** [comment]
Hi @Clivern Happy to take this up for #Hacktoberfest! 

If I may ask, why AOSP style and not say Google Java Style guide, since this is not an Android project?

**Comment by Clivern** [comment]
Sure you can take this over and https://github.com/Clivern/Racter/issues/13. I chosen the AOSP style because it is more readable. I kind of hate the google style with the 2 whitespace ident. But you can use it indeed for a PR.

I was thinking to use https://github.com/sherter/google-java-format-gradle-plugin. I used it somewhere else and works as expected.

Here's part of my `build.gradle`
```groovy
plugins {
    id 'com.github.sherter.google-java-format' version '0.8'
}

googleJavaFormat {
  options style: 'AOSP'
}
```

It gives you two gradle tasks to format & verify

```bash
$ ./gradlew goJF --info
```

```bash
$ ./gradlew verGJF --info
```

**Comment by IEnoobong** [comment]
Great, A number of folks have issues with the 2 whitespace indent too 😄. I'll begin with it from the when #Hacktoberfest begins using the google java format
